version: '3'

services:

  advertisement_manager_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: advertisement_manager_db
    ports:
      - "3306:3306"